approval_policy = "on-request"
model_reasoning_summary = "detailed"
model_supports_reasoning_summaries = true
model_verbosity = "medium"
model = "gpt-5.5"
model_reasoning_effort = "medium"

sandbox_mode = "workspace-write"
web_search = "live"

notify = ["/Users/jessearmand/.codex/plugins/cache/openai-bundled/computer-use/1.0.758/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[features]
apps = true
multi_agent = true
memories = true

[history]
persistence = "save-all"

[mcp_servers.chrome-devtools]
args = [
    "-y",
    "chrome-devtools-mcp@latest"
]
command = "npx"
enabled = true

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.env_http_headers]
CONTEXT7_API_KEY = "CONTEXT7_API_KEY"

[mcp_servers.gh-grep]
url = "https://mcp.grep.app"

[model_providers.arceeai]
base_url = "https://conductor.arcee.ai/v1"
env_key = "ARCEEAI_API_KEY"
name = "ArceeAI"

[model_providers.azure]
base_url = "https://YOUR_PROJECT_NAME.openai.azure.com/openai"
env_key = "AZURE_OPENAI_API_KEY"
name = "AzureOpenAI"

[model_providers.deepseek]
base_url = "https://api.deepseek.com"
env_key = "DEEPSEEK_API_KEY"
name = "DeepSeek"

[model_providers.gemini]
base_url = "https://generativelanguage.googleapis.com/v1beta/openai"
env_key = "GEMINI_API_KEY"
name = "Gemini"

[model_providers.groq]
base_url = "https://api.groq.com/openai/v1"
env_key = "GROQ_API_KEY"
name = "Groq"

[model_providers.mistral]
base_url = "https://api.mistral.ai/v1"
env_key = "MISTRAL_API_KEY"
name = "Mistral"

[model_providers.moonshotai]
base_url = "https://api.moonshot.ai/v1"
env_key = "MOONSHOT_API_KEY"
name = "MoonshotAI"

[model_providers.openrouter]
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"
name = "OpenRouter"

[model_providers.xai]
base_url = "https://api.x.ai/v1"
env_key = "XAI_API_KEY"
name = "xAI"

[model_providers.zai]
base_url = "https://api.z.ai/api/paas/v4/"
env_key = "ZAI_API_KEY"
name = "Z.AI"

[plugins."github@openai-curated"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."hugging-face@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[sandbox_workspace_write]
network_access = true

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
RIPGREP_CONFIG_PATH = "/Users/jessearmand/.ripgreprc"

